sudo: required
services:
    - docker
before_install:
    # yarn create react-app fib-app 
    - docker build -t danbo62/react-test -f ./fib-app/Dockerfile.dev ./fib-app

script:
    - docker run danbo62/react-test yarn test -- --coverage

after_sucess:
    - docker build -t danbo62/complex2:fib-app ./fib-app
    - docker build -t danbo62/complex2:nginx ./nginx
    - docker build -t danbo62/complex2:server ./server
    - docker build -t danbo62/complex2:worker ./worker
    # Log in to danbo62 docker CLI, NOTE: user/pwd encryted and stored in my Travis-CI.
    - echo "$DOCKER-PWD" | docker login -u "$DOCKER-ID" --password-stdin
    # Now push images to danbo62 DockerHub; docker push danbo62/complex2:tagname
    - docker push danbo62/complex2:fib-app # pusing the build tags -t
    - docker push danbo62/complex2:nginx
    - docker push danbo62/complex2:server
    - docker push danbo62/complex2:worker


