# Ref: https://config.travis-ci.com/
sudo: required  # Depreciated according to Ref
# version: 1.0  # Beta Opt-In ; Travis Build Config Validation ; Requires secure API keys
os: linux   # This is default
dist: bionic ;
language: java
    
services:
    - docker
before_install:
    # yarn create react-app fib-app 
    # NOTE: Travis-CI runs this file, therefor this is the "root Path".
    #       Project path is relative!
    - docker build -t danbo62/react-test -f ./fib-app/Dockerfile.dev ./fib-app

script: # This is the main test section
    - docker run danbo62/react-test yarn test -- --coverage

after_sucess:
    # build the production images and send to your DockerHub Repo
    # Format below means:
        # no -f override so use default prod Dockerfile
        # -t <DockerID/Reponame-image> ; Must be created on Dockerhub !
        # ./<build context>
    - docker build -t danbo62/multi-fib-app ./fib-app
    - docker build -t danbo62/multi-nginx ./nginx
    - docker build -t danbo62/multi-server ./server
    - docker build -t danbo62/multi-worker ./worker
    # Log in to danbo62 docker CLI, NOTE: user/pwd encryted and stored in my Travis-CI as Vars.
    # Travis-CI requires and escape char "\" for $VAR.
     - echo "$DOCKER-PWD" | docker login -u "$DOCKER-ID" --password-stdin # Not secure!
    # Now push images to danbo62 DockerHub; docker push danbo62/<repoName>:tagname ; using default latest
    - docker push danbo62/multi-fib-app:latest # pushing the images to Dockerhub
    - docker push danbo62/multi-nginx:latest
    - docker push danbo62/multi-server:latest
    - docker push danbo62/multi-worker:latest

    deploy:
        provider: elasticbeanstalk
        region: us-west-1
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-west-2-923435484303
        bucket_path: docker-multi
        on:
            branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY





